---
title: "Change Log"
output: 
  html_document: 
    highlight: null
    theme: null
---

## 2021-Mar-11: Initial Release
Initial results provided from 8 databases.

## 2021-Mar-18: Adding results
Now showing results from 10 databases for task #3.

## 2021-Apr-06: Adding and correcting results
Now showing task #3 results from 8 databases with correct time-to-event data.

## 2021-Apr-30: Adding pre-task#4 results
Now showing results for pre-task#4 for 7 databases.

## 2021-Jul-15: Adding task #5 results & bug fixes
Now showing results for task #5 for 5 databases.
Some bugs fixed from the previous version.

## 2021-Oct-14: Aligning with the package v0.4.4 
Updates to time to event analysis & fixes to cohort characterization & comparison.

## 2021-Nov-09: Data update
Triggering the data update to show results with correct clinical characterization.

## 2021-Nov-15: Data update
Triggering the data update to show results with correct clinical characterization.

## 2021-Nov-30: Data update
Data update to show results from 11 databases with version 0.4.4.

## 2021-Dec-06: Data update
Data update to show results form 12 databases with version 0.4.4.
------
