---
title: "Phenotype Summary Example Template"
author: "Author: Example Author"
date: "Date: February 26, 2019"
bibliography: example_bibliography_phenotype.bib
output:
  html_fragment # Must be a fragment in order to be properly embedded into the Shiny app
---

# Summary

## Phenotype Title
Rheumatoid Arthritis

## Link to GitHub
[Link to Phenotype GitHub Page](https://www.github.com)

## Author(s) and Affiliations
Author 1, Author 2, etc.

## Date Added:
February 21, 2019

## Purpose
This definition is intended to capture patients with a first-observed diagnosis of chronic rheumatoid arthritis (RA), taking care to rule out patients with short-term joint pain or fibromyalgia.

## Method
This phenotype was developed by a group of 4 expert rheumatologists, who gathered and identified key condition codes that manifest in individuals with RA, along with drug combinations that almost exclusively identify RA patients.

# Data

## Hash of Implementation
7245cf0ee90b52deb5b9965f42a5f32cff585d29

## Modality
Rule-Based

## Etc

### Possibility of including Graphics/Diagrams
This is an R Markdown file, so...

Graphics, like flowcharts can be included directly:
```{r example_gfx}
knitr::include_graphics("example_diagram.png")
```

### Possibility of including R code

Most R code, in principle, can be included too if need be:
```{r example_r}
print(mean(1:10))

head(iris)
```

### Possibility of including citations
Suppose in our write-up, we wish to include references, such as [@OHDSI1] and [@OHDSI2].

The references below are automatically generated by cross-referencing a separate BibTex file.

# References
